<?php

namespace Database\Seeders;

use App\Models\MedicalEspecialties;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        if (! User::query()->where('email', 'superusuario@test.com')->exists()) {
            User::factory()->superusuario()->create();
        }

        if (! User::query()->where('email', 'admin@test.com')->exists()) {
            User::factory()->administrador()->create();
        }

        if (! User::query()->where('email', 'doctor@test.com')->exists()) {
            User::factory()->doctor()->create();
        }

        if (! User::query()->where('email', 'paciente@test.com')->exists()) {
            User::factory()->paciente()->create();
        }

        if (! User::query()->where('email', 'enfermeria@test.com')->exists()) {
            User::factory()->enfermeria()->create();
        }

        if (! User::query()->where('email', 'asistencial@test.com')->exists()) {
            User::factory()->asistencial()->create();
        }

        User::factory()
            ->count(30)
            ->afterCreating(function (User $user): void {
                $role = Role::query()->firstOrCreate(
                    ['slug' => 'paciente'],
                    ['name' => 'Paciente']
                );
                $user->roles()->sync([$role->id]);
            })
            ->create();

        $this->seedDefaultModules();
        $this->seedMedicalEspecialties();
    }

    /**
     * Default modules that are accessible from the administrator dashboard.
     * The list mirrors the CRUD modules generated by `php artisan make:crud <Model>`.
     *
     * @var list<array{name: string, description: string}>
     */
    private array $defaultModules = [
        ['name' => 'Users', 'description' => 'Manage system users'],
        ['name' => 'Roles', 'description' => 'Manage user roles'],
        ['name' => 'Permissions', 'description' => 'Manage system permissions'],
        ['name' => 'Modules', 'description' => 'Generate new CRUD modules'],
    ];

    /**
     * Insert the default modules if they do not already exist.
     */
    private function seedDefaultModules(): void
    {
        $now = now();

        foreach ($this->defaultModules as $row) {
            $slug = Str::slug($row['name']);

            if (DB::table('modules')->where('name', $row['name'])->exists()) {
                continue;
            }

            DB::table('modules')->insert([
                'name' => $row['name'],
                'description' => $row['description'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }

    /**
     * Insert the default medical specialties (factory seed state) if the table is empty.
     */
    private function seedMedicalEspecialties(): void
    {
        if (MedicalEspecialties::query()->exists()) {
            return;
        }

        MedicalEspecialties::factory()->count(5)->seed()->create();
    }
}
