<?php

namespace Database\Seeders;

use App\Models\MedicalEspecialties;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        if (! User::query()->where('email', 'superusuario@test.com')->exists()) {
            User::factory()->superusuario()->create();
        }

        if (! User::query()->where('email', 'admin@test.com')->exists()) {
            User::factory()->administrador()->create();
        }

        if (! User::query()->where('email', 'doctor@test.com')->exists()) {
            User::factory()->doctor()->create();
        }

        if (! User::query()->where('email', 'paciente@test.com')->exists()) {
            User::factory()->paciente()->create();
        }

        if (! User::query()->where('email', 'enfermeria@test.com')->exists()) {
            User::factory()->enfermeria()->create();
        }

        if (! User::query()->where('email', 'asistencial@test.com')->exists()) {
            User::factory()->asistencial()->create();
        }

        User::factory()
            ->count(30)
            ->afterCreating(function (User $user): void {
                $role = Role::query()->firstOrCreate(
                    ['slug' => 'paciente'],
                    ['name' => 'Paciente']
                );
                $user->roles()->sync([$role->id]);
            })
            ->create();

        $this->seedModules();
        $this->seedPermissions();
        $this->seedSuperuserAssociations();
        $this->seedMedicalEspecialties();
    }

    /**
     * Insert the default modules declared in
     * `database/seeders/data/modules.php`, creating new rows when
     * missing and **updating `display_name` / `description` on
     * existing rows** so the localised labels stay in sync with
     * the seed data file.
     *
     * The list mirrors every CRUD module generated by
     * `php artisan make:crud <Model>`. The make:crud command
     * appends the new module to that file so the registry survives
     * `migrate:fresh`.
     */
    private function seedModules(): void
    {
        $modules = $this->loadSeedData('modules.php');

        if ($modules === []) {
            return;
        }

        $now = now();

        foreach ($modules as $row) {
            $existing = DB::table('modules')->where('name', $row['name'])->first();

            if ($existing) {
                // Keep the row id and created_at, but refresh the
                // localised display_name/description so re-running
                // `db:seed` (after editing the seed data file)
                // actually propagates the new labels.
                $updates = [];
                if (array_key_exists('display_name', $row) && $row['display_name'] !== null) {
                    $updates['display_name'] = $row['display_name'];
                }
                if (array_key_exists('description', $row) && $row['description'] !== null) {
                    $updates['description'] = $row['description'];
                }
                if ($updates !== []) {
                    $updates['updated_at'] = $now;
                    DB::table('modules')->where('name', $row['name'])->update($updates);
                }

                continue;
            }

            DB::table('modules')->insert([
                'name' => $row['name'],
                'display_name' => $row['display_name'] ?? null,
                'description' => $row['description'] ?? null,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }

    /**
     * Insert the default permissions declared in
     * `database/seeders/data/permissions.php` if they do not already exist.
     *
     * The list mirrors every CRUD module generated by
     * `php artisan make:crud <Model>`. The make:crud command appends the
     * new module's CRUD permissions to that file so the registry survives
     * `migrate:fresh`.
     */
    private function seedPermissions(): void
    {
        $permissions = $this->loadSeedData('permissions.php');

        if ($permissions === []) {
            return;
        }

        $now = now();

        foreach ($permissions as $row) {
            if (DB::table('permissions')->where('slug', $row['slug'])->exists()) {
                continue;
            }

            DB::table('permissions')->insert([
                'name' => $row['name'],
                'slug' => $row['slug'],
                'module' => $row['module'],
                'description' => $row['description'] ?? null,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }

    /**
     * Load a seed data file from `database/seeders/data/`.
     *
     * @return array<int, array<string, mixed>>
     */
    private function loadSeedData(string $filename): array
    {
        $path = database_path('seeders/data/'.$filename);

        if (! file_exists($path)) {
            return [];
        }

        $data = require $path;

        return is_array($data) ? $data : [];
    }

    /**
     * Attach every module and every permission to the `superusuario`
     * role so it always has full access to the system.
     *
     * Mirrors the logic of the
     * `2026_07_31_000002_seed_superuser_module_associations` migration
     * so the associations are also rebuilt on every `migrate:fresh --seed`
     * without having to re-run the migration manually.
     */
    private function seedSuperuserAssociations(): void
    {
        $superuser = DB::table('roles')->where('slug', Role::SUPERUSER_SLUG)->first();

        if ($superuser === null) {
            return;
        }

        $now = now();

        // 1) Attach every module to the superusuario role.
        $modules = DB::table('modules')->select('id')->get();
        foreach ($modules as $module) {
            $exists = DB::table('roles_modules')
                ->where('role_id', $superuser->id)
                ->where('module_id', $module->id)
                ->exists();

            if ($exists) {
                continue;
            }

            DB::table('roles_modules')->insert([
                'role_id' => $superuser->id,
                'module_id' => $module->id,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        // 2) Attach every permission of every module to the superusuario role.
        $permissions = DB::table('permissions')->select('id', 'module')->get();
        $moduleIdsByName = DB::table('modules')->pluck('id', 'name')->all();

        foreach ($permissions as $permission) {
            $moduleId = $moduleIdsByName[$permission->module] ?? null;

            if ($moduleId === null) {
                continue;
            }

            $exists = DB::table('roles_modules_permissions')
                ->where('role_id', $superuser->id)
                ->where('module_id', $moduleId)
                ->where('permission_id', $permission->id)
                ->exists();

            if ($exists) {
                continue;
            }

            DB::table('roles_modules_permissions')->insert([
                'role_id' => $superuser->id,
                'module_id' => $moduleId,
                'permission_id' => $permission->id,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }

    /**
     * Insert the default medical specialties (factory seed state) if the table is empty.
     */
    private function seedMedicalEspecialties(): void
    {
        if (MedicalEspecialties::query()->exists()) {
            return;
        }

        MedicalEspecialties::factory()->count(5)->seed()->create();
    }
}
