<?php

/**
 * Default modules registered for the application.
 *
 * The list mirrors every CRUD module generated by
 * `php artisan make:crud <Model>`. When `make:crud` finishes its
 * scaffolding, it appends the new module here so that
 * `migrate:fresh --seed` keeps the system registry up to date.
 *
 * @var list<array{name: string, display_name: string, description: string}>
 */
return [
    ['name' => 'users',        'display_name' => 'Users',        'description' => 'Gestión y administración de Users.'],
    ['name' => 'roles',        'display_name' => 'Roles',        'description' => 'Gestión y administración de Roles.'],
    ['name' => 'permissions',  'display_name' => 'Permissions',  'description' => 'Gestión y administración de Permissions.'],
    ['name' => 'modules',      'display_name' => 'Modules',      'description' => 'Gestión y administración de Modules.'],
    ['name' => 'patients',     'display_name' => 'Patients',     'description' => 'Gestión y administración de Patients.'],
    ['name' => 'doctors',      'display_name' => 'Doctors',      'description' => 'Gestión y administración de Doctors.'],
    ['name' => 'medical_especialties', 'display_name' => 'Medical Especialties', 'description' => 'Gestión y administración de Medical Especialties.'],
    ['name' => 'allergies', 'display_name' => 'Allergies', 'description' => 'Gestión y administración de Allergies.'],
];
