<?php

/**
 * Default modules registered for the application.
 *
 * The list mirrors every CRUD module generated by
 * `php artisan make:crud <Model>`. When `make:crud` finishes its
 * scaffolding, it appends the new module here so that
 * `migrate:fresh --seed` keeps the system registry up to date.
 *
 * @var list<array{name: string, display_name: string, description: string}>
 */
return [
    ['name' => 'users',        'display_name' => 'Usuarios',        'description' => 'Gestión y administración de Usuarios.'],
    ['name' => 'roles',        'display_name' => 'Roles',           'description' => 'Gestión y administración de Roles.'],
    ['name' => 'permissions',  'display_name' => 'Permisos',        'description' => 'Gestión y administración de Permisos.'],
    ['name' => 'modules',      'display_name' => 'Módulos',         'description' => 'Gestión y administración de Módulos.'],
    ['name' => 'allergies', 'display_name' => 'Alergias', 'description' => 'Gestión y administración de Alergias.'],
    ['name' => 'doctors', 'display_name' => 'Doctores', 'description' => 'Gestión y administración de Doctores.'],
    ['name' => 'medical-specialties', 'display_name' => 'Especialidades Médicas', 'description' => 'Gestión y administración de Especialidades Médicas.'],
    ['name' => 'states', 'display_name' => 'Estados', 'description' => 'Gestión y administración de Estados.'],
    ['name' => 'municipalities', 'display_name' => 'Municipios', 'description' => 'Gestión y administración de Municipios.'],
    ['name' => 'health-backgrounds', 'display_name' => 'Antecedentes de Salud', 'description' => 'Gestión y administración de Antecedentes de Salud.'],


];
