<?php

/**
 * Default permissions registered for the application.
 *
 * The list mirrors every CRUD module generated by
 * `php artisan make:crud <Model>`. When `make:crud` finishes its
 * scaffolding, it appends the new module's CRUD permissions here so
 * that `migrate:fresh --seed` keeps the system registry up to date.
 *
 * Each entry uses the format:
 *   ['name' => 'View', 'slug' => 'module.read', 'module' => 'module', 'description' => '...']
 *
 * @var list<array{name: string, slug: string, module: string, description: string}>
 */
return [
    // Users
    ['name' => 'View',           'slug' => 'users.read',           'module' => 'users',           'description' => 'View the users list and details'],
    ['name' => 'Create',         'slug' => 'users.create',         'module' => 'users',           'description' => 'Create new users'],
    ['name' => 'Update',         'slug' => 'users.update',         'module' => 'users',           'description' => 'Edit existing users'],
    ['name' => 'Delete',         'slug' => 'users.delete',         'module' => 'users',           'description' => 'Delete users'],
    ['name' => 'Assign Role',    'slug' => 'users.assignRole',     'module' => 'users',           'description' => 'Change a user role'],
    ['name' => 'Reset Password', 'slug' => 'users.resetPassword',  'module' => 'users',           'description' => 'Reset a user password'],

    // Roles
    ['name' => 'View',                'slug' => 'roles.read',                'module' => 'roles', 'description' => 'View the roles list and details'],
    ['name' => 'Create',              'slug' => 'roles.create',              'module' => 'roles', 'description' => 'Create new roles'],
    ['name' => 'Update',              'slug' => 'roles.update',              'module' => 'roles', 'description' => 'Edit existing roles'],
    ['name' => 'Delete',              'slug' => 'roles.delete',              'module' => 'roles', 'description' => 'Delete roles'],
    ['name' => 'Assign Permissions',  'slug' => 'roles.assignPermissions',   'module' => 'roles', 'description' => 'Assign permissions to a role'],

    // Permissions
    ['name' => 'View',   'slug' => 'permissions.read',   'module' => 'permissions', 'description' => 'View the permissions list'],
    ['name' => 'Create', 'slug' => 'permissions.create', 'module' => 'permissions', 'description' => 'Create new permissions'],
    ['name' => 'Update', 'slug' => 'permissions.update', 'module' => 'permissions', 'description' => 'Edit existing permissions'],
    ['name' => 'Delete', 'slug' => 'permissions.delete', 'module' => 'permissions', 'description' => 'Delete permissions'],

    ['name' => 'View', 'slug' => 'allergies.read', 'module' => 'allergies', 'description' => 'View the Allergies list and details'],
    ['name' => 'Create', 'slug' => 'allergies.create', 'module' => 'allergies', 'description' => 'Create new Allergies'],
    ['name' => 'Update', 'slug' => 'allergies.update', 'module' => 'allergies', 'description' => 'Edit existing Allergies'],
    ['name' => 'Delete', 'slug' => 'allergies.delete', 'module' => 'allergies', 'description' => 'Delete Allergies'],
    // Doctores
    ['name' => 'View',   'slug' => 'doctors.read',   'module' => 'doctors', 'description' => 'View the Doctores list and details'],
    ['name' => 'Create', 'slug' => 'doctors.create', 'module' => 'doctors', 'description' => 'Create new Doctores'],
    ['name' => 'Update', 'slug' => 'doctors.update', 'module' => 'doctors', 'description' => 'Edit existing Doctores'],
    ['name' => 'Delete', 'slug' => 'doctors.delete', 'module' => 'doctors', 'description' => 'Delete Doctores'],
    // Especialidades Médicas
    ['name' => 'View',   'slug' => 'medical-specialties.read',   'module' => 'medical-specialties', 'description' => 'View the Especialidades Médicas list and details'],
    ['name' => 'Create', 'slug' => 'medical-specialties.create', 'module' => 'medical-specialties', 'description' => 'Create new Especialidades Médicas'],
    ['name' => 'Update', 'slug' => 'medical-specialties.update', 'module' => 'medical-specialties', 'description' => 'Edit existing Especialidades Médicas'],
    ['name' => 'Delete', 'slug' => 'medical-specialties.delete', 'module' => 'medical-specialties', 'description' => 'Delete Especialidades Médicas'],
];
